export const START_LOGIN = 'START_LOGIN';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';

export const START_LOAD_CATEGORIES = 'START_LOAD_CATEGORIES';
export const START_LOAD_POSTS = 'START_LOAD_POSTS';
export const START_LOAD_COMMENTS = 'START_LOAD_COMMENTS';

export const CATEGORIES_LOADED = 'CATEGOARIES_LOADED';
export const POSTS_LOADED = 'POSTS_LOADED';
export const COMMENTS_LOADED = 'COMMENT_LOADED';
