export const SESSION_NOT_STARTED = 'SESSION_NOT_STARTED';
export const SESSION_ACCESSING = 'SESSION_ACCESSING';
export const SESSION_START = 'SESSION_START';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_TERMINATED = 'SESSION_TERMINATED';
export const SESSION_USER_CREATED = 'SESSION_USER_CREATED';
export const SESSION_USER_NOT_CREATED = 'SESSION_USER_NOT_CREATED';

export const START_LOAD_CATEGORIES = 'START_LOAD_CATEGORIES';
export const START_LOAD_POSTS = 'START_LOAD_POSTS';
export const START_LOAD_COMMENTS = 'START_LOAD_COMMENTS';

export const CATEGORIES_LOADED = 'CATEGOARIES_LOADED';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_LOAD_FAILED = 'POSTS_LOAD_FAILED';
export const NEW_POST = 'NEW_POST';
export const POST_CREATING = 'POST_CREATING';
export const POST_CREATED = 'POST_CREATED';
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED';
export const POST_VOTE = 'POST_VOTE';
export const POST_VOTING = 'POST_VOTING';
export const POST_VOTED = 'POST_VOTED';
export const POST_VOTE_FAILED = 'POST_VOTE_FAILED';

export const COMMENTS_LOADED = 'COMMENT_LOADED';
