export const SESSION_NOT_STARTED = 'SESSION_NOT_STARTED';
export const SESSION_ACCESSING = 'SESSION_ACCESSING';
export const SESSION_START = 'SESSION_START';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_USER_CREATED = 'SESSION_USER_CREATED';
export const SESSION_USER_NOT_CREATED = 'SESSION_USER_NOT_CREATED';

export const START_LOAD_CATEGORIES = 'START_LOAD_CATEGORIES';
export const START_LOAD_POSTS = 'START_LOAD_POSTS';

export const CATEGORIES_LOADED = 'CATEGOARIES_LOADED';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_LOAD_FAILED = 'POSTS_LOAD_FAILED';
export const NEW_POST = 'NEW_POST';
export const POST_CREATING = 'POST_CREATING';
export const POST_CREATED = 'POST_CREATED';
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED';
export const POST_DETAILS_LOADING = 'POST_DETAILS_LOADING';
export const POST_DETAILS_LOADED = 'POST_DETAILS_LOADED';
export const POST_DETAILS_LOAD_FAILED = 'POST_DETAILS_LOAD_FAILED';
export const POST_VOTING = 'POST_VOTING';
export const POST_VOTE_FAILED = 'POST_VOTE_FAILED';
export const POST_UPDATING = 'POST_UPDATING';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_DELETING = 'POST_DELETING';
export const POST_DELETED = 'POST_DELETED';

export const COMMENT_LOADING = 'COMMENT_LOADING';
export const COMMENT_LOADED = 'COMMENT_LOADED';
export const COMMENT_CREATING = 'COMMENT_CREATING';
export const COMMENT_CREATED = 'COMMENT_CREATED';
export const COMMENT_UPDATING = 'COMMENT_UPDATING';
export const COMMENT_UPDATED = 'COMMENT_UPDATED';
export const COMMENT_DELETING = 'COMMENT_DELETING';
export const COMMENT_DELETED = 'COMMENT_DELETED';
export const COMMENT_VOTING = 'COMMENT_VOTING';
export const COMMENT_VOTED = 'COMMENT_VOTED';
